name: niobiumcoconut-lucid
version: '0.1.0.0'
author: HaskellNixCabalStarter
maintainer: HaskellNixCabalStarter
license: MIT
dependencies:
- base >=4.12 && <4.13
- lucid
- actiniumbravohoneydew
- string-conversions
- niobiumcoconut
library:
  source-dirs: src
